FROM cogniteev/oracle-java:java8

WORKDIR /mantis

ARG MANTIS_VERSION

RUN export \
    && wget https://github.com/input-output-hk/plato/archive/v$MANTIS_VERSION/mantis-$MANTIS_VERSION.zip \
    && apt-get update \ 
    && apt-get install unzip \
    && apt-get clean \
    && unzip mantis-$MANTIS_VERSION.zip

WORKDIR mantis-$MANTIS_VERSION
ENTRYPOINT ["sh", "-c", "./bin/mantis -J-Dmantis.network.rpc.port=$RPC_PORT -J-Dmantis.datadir=/datadir -J-Dmantis.network.rpc.interface=0.0.0.0 -J-Dmantis.network.server-address.interface=0.0.0.0"]